# Generated by Django 4.0.3 on 2022-03-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_seen',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
