<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-03-28 10:55
=======
# Generated by Django 4.0.3 on 2022-03-28 10:02
>>>>>>> ca481e019e8f867c9a069d0e3508f5bde61d3994

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_seen',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
