# Generated by Django 4.0.3 on 2022-03-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=150)),
                ('subject', models.TextField()),
                ('messages', models.TextField()),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
